spring:
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 10s
      thread-name-prefix: task-
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demodb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    cluster:
      nodes: 192.168.203.210:7001,192.168.203.211:7001,192.168.203.212:7001,192.168.203.210:7002,192.168.203.211:7002,192.168.203.212:7002
    password:
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000ms
    timeout: 2000ms

mybatis:
  mapper-locations: classpath*:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.model.entity  # 注意：对应实体类的路径

logging:
  level:
    com:
      example:
        demo:
          mapper: debug